#!/bin/bash

cd dist

find . -name "*.js" -type f -print0 | xargs -0 /bin/rm -f
find . -name "*.js.map" -type f -print0 | xargs -0 /bin/rm -f
find . -name "*.d.ts" -type f -print0 | xargs -0 /bin/rm -f

cd ../
